name: replant_frontend
description: RePlant Flutter 프로젝트
version: 1.0.0

environment:
  sdk: "^3.8.0"

flutter:
  assets:
    - assets/Replant_logo.png
    - assets/kakao_login.png
    - assets/Naver_login.png

dev_dependencies:
  flutter_native_splash: ^2.3.10

flutter_native_splash:
  image: assets/Replant_logo.png
  color: "#ffffff"
